# imports

def get(malware):
    metadata.get(malware)
    fileheader.get(malware)
    optheader.get(malware)
    sections.get(malware)
    imphash.get(malware)
    imports.get(malware)
    exports.get(malware)
    antidbg.get(malware)
    antivm.get(malware)
    apialert.get(malware)
    codeint.get(malware)
    cfg.get(malware)
    dep.get(malware)
    aslr.get(malware)
    seh.get(malware)
    gs.get(malware)
    tls.get(malware)
    codeint.get(malware)
    dbgts.get(malware)
    url.get(malware)
    manifest.get(malware)
    version.get(malware)
    badstr.get(malware)
    packed.get(malware)
    certificate.get(malware)
    virustotal.get(malware)
    # yarar.get(malware)
